# Reference: 
# https://docs.docker.com/build/ci/github-actions/update-dockerhub-desc/
# https://github.com/peter-evans/dockerhub-description

name: docker-image-readme
concurrency: deploy-${{ github.workflow }}

on: 
  push:
    branches:
      - main
    paths:
      - README.md
env:
  IMAGE_CONTEXT: ./docker/az-pwsh
  REGISTRY_IMAGE: ${{ github.repository_owner }}/az-pwsh

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.REGISTRY_IMAGE }}
